### ISSUE TITLE
Site will need search functionality

### ISSUE THREAD

**Issue by castrojo** [kubernetes-sigs/contributor-site#4]
We need to figure out how to use a search engine effectively for the site.

**Comment by mrbobbytables** [comment]
Something we should consider when implementing the search functionality is the integration of an alternate search engine for Chinese users. 

This is currently being discussed (with bing being the preferred alternative) over in k/website:

https://github.com/kubernetes/website/issues/9635

**Comment by whs-dot-hk** [comment]
I speak chinese what can I do to help?

**Comment by mrbobbytables** [comment]
@whs-dot-hk Currently, the site does not have search functionality. 

The theme currently being used **does** have an integrated search capability, but it drastically increases page load time =/ and has since been disabled (Long story short, every page winds up loading the entire site...about 4MB of extra content for EVERY page).

Ideally the contributor-site would mimic https://kubernetes.io with an embedded google search. However, embedded google search appears to be blocked in China. The solution being proposed in https://github.com/kubernetes/website/issues/9635 and its associated PR https://github.com/kubernetes/website/pull/9845 is to detect the region and enable using bing search instead.

So, this issue has two big tasks:
* Replace integrated theme search with google embedded search.
* Mimic the functionality being developed in k/website to swap search engines based on region.

If you'd like to take a stab at either of those, it'd definitely be appreciated :)

**Comment by nimbinatus** [comment]
Thought on this one: Most static site generators can generate a sitemap. If Hugo can generate a JSON sitemap (and I'm pretty sure that such a sitemap could be generated in different languages), a JS search function can search the static file and speed up search and load time. The long timeframe is then offset into the generation time, which the end user won't see.

**Comment by mrbobbytables** [comment]
We had the json sitemap initially, but when we loaded in both the contributor and developer guide it drastically decreased the performance of the site (it was like a 1mb json blob). =/

It'll probably be fine for the interim with the drastically cut down content that we have in there, but might crop up again in the future.

**Comment by nimbinatus** [comment]
🤔 Interesting. I wonder why that is. I'll poke around.

**Comment by mrbobbytables** [comment]
Follow up to the javascript search --
I went back and looked, it was actually probably because we were ingesting pretty much all of the kubernetes community and enhancement repos. I think it was because that altogether is ALOT of markdown. I think for the content we plan to ingest at this point the javascript search will be fine. 👍

**Comment by mrbobbytables** [comment]
This will be resolved with the migration to docsy. For now I'm going to close this out.

/close
